### ISSUE TITLE
Recent Apps and Most Used have missing icons

### ISSUE THREAD

**Issue by Conanzhou** [Zren/plasma-applet-tiledmenu#76] opened 2020-07-03 05:06 UTC
There is no icon in Recent Apps and Most Used within KDE 5.71.0 / Plasma 5.19.2.
![Screenshot_20200703_130507](https://user-images.githubusercontent.com/26038834/86433699-05b33f80-bd2e-11ea-8a8e-ce6190600eda.png)

**Comment by Zren** [comment] 2020-07-03 05:45
Pin a recent app to the menu, then right click > Edit Tile? What's the url?

**Comment by Conanzhou** [comment] 2020-07-03 06:01
> Pin a recent app to the menu, then right click > Edit Tile? What's the url?
It's "google-chrome-unstable.desktop"

**Comment by Zren** [comment] 2020-07-03 06:13
Damn, I was hoping the bug was `applications:google-chrome-unstable.desktop` like another recent bug.

It sounds like there's a bug in my icon code in `MenuListItem.qml`

```
	// We need to look at the js list since ListModel doesn't support item's with non primitive propeties (like an Image).
	property bool modelListPopulated: !!listView.model.list && listView.model.list.length - 1 >= index
	property var iconInstance: modelListPopulated && listView.model.list[index] ? listView.model.list[index].icon : ""
	Connections {
		target: listView.model
		onRefreshed: {
			// We need to manually trigger an update when we update the model without replacing the list.
			// Otherwise the icon won't be in sync.
			itemDelegate.iconInstance = listView.model.list[index] ? listView.model.list[index].icon : ""
		}
	}
```

**Comment by Zzombiee2361** [comment] 2020-07-16 03:40
![Screenshot_20200716_103726](https://user-images.githubusercontent.com/37852137/87623918-a8b58180-c750-11ea-8ca6-2452779b6e61.png)
Can confirm

**Comment by matty-r** [comment] 2020-07-20 23:32
I'm also having this issue. It didn't occur until I updated my system yesterday.

Operating System: Manjaro Linux
KDE Plasma Version: 5.19.3
KDE Frameworks Version: 5.72.0
Qt Version: 5.15.0
Kernel Version: 5.7.9-1-MANJARO
Tiled Menu Version: 38

**Comment by Zren** [comment] 2020-07-21 00:27
Just updated Manjaro to, and can reproduce. Will test later.

**Comment by Zren** [comment] 2020-07-21 01:09
Ah, it seems the recent usage model passes `iconName` instead of an icon instance now. At some point I must have removed the fallback logic as I've always parsed the iconName as well.

https://github.com/Zren/plasma-applet-tiledmenu/blob/master/package/contents/ui/KickerListModel.qml#L57

```
qml: AppsModel(0x559becf1a8c0) 19 (name= Winetricks , iconName= undefined , icon= QVariant(QIcon, QIcon("winetricks",availableSizes[normal,Off]=(QSize(16, 16), ...)) )
qml: AppsModel(0x559becf78730) 0 (name= Battle.net , iconName= undefined , icon= QVariant(QIcon, QIcon("56B4_Battle.net Launcher.0",availableSizes[normal,Off]=(QSize(16, 16), ...)) )
qml: RecentUsageModel(0x559bece85250) 0 (name= Dolphin , iconName= system-file-manager , icon= undefined )
qml: RecentUsageModel(0x559bece85250) 1 (name= Firefox , iconName= firefox , icon= undefined )
qml: RecentUsageModel(0x559bece85250) 2 (name= Window Decorations , iconName= preferences-desktop-theme-windowdecorations , icon= undefined )
```

**Comment by Zren** [comment] 2020-07-21 01:16
This was probably caused by this commit, though it's from Plasma 5.19.1 which doesn't sound right, as I only just experienced it.

* https://github.com/KDE/plasma-workspace/commit/ba44b69abf82b1236ffab7d8683728c142d30c52#diff-ad8dc038e5949e5d4770ffa1c7a044b2
* https://github.com/KDE/plasma-workspace/commits/master/applets/kicker/plugin/recentusagemodel.cpp
* https://github.com/KDE/plasma-workspace/blame/master/applets/kicker/plugin/recentusagemodel.cpp

**Comment by matty-r** [comment] 2020-07-21 05:16
I added your patch manually and confirm that it fixed the issue.

**Comment by Zren** [comment] 2020-07-22 17:35
Fixed in v39

**Closed** 2020-07-22 17:35 UTC
